- name: Prepare the code to run on the remote
  hosts: all
  tasks:
    - name: Install yum packages
      ansible.builtin.yum:
        name: "{{ packages }}"
      become: true
      vars:
        packages:
        - python
        - python-pip
        - unzip
        - wget
        - git
    
    - name: Install general Python packages
      ansible.builtin.pip:
        name:
          - scipy
          - numpy
          - awscli
          - biopython
        state: present
    
    - name: Install PyTorch (CPU version)
      ansible.builtin.pip:
        name: torch
        extra_args: "--index-url https://download.pytorch.org/whl/cpu"
        state: present


    - name: Download repo of assigning task from github
      git:
        repo: "https://github.com/mruiyangyou/comp02530test"
        dest: "~/comp0235test"